# @file .github/workflows/ci.yml
# @stamp {"ts":"2025-10-30T22:55:00Z"}
# @architectural-role Configuration
# @description Defines the Continuous Integration (CI) pipeline. It runs on every push and pull request to ensure code quality by linting, building, and running the full test suite.
# @core-principles
#   1. IS the single source of truth for the project's automated quality checks.
#   2. MUST run on every push and pull request to the `main` branch.
#   3. OWNS the responsibility for verifying the integrity of the codebase before deployment.
# @api-declaration
#   - Not applicable. This is a workflow triggered by GitHub repository events.
# @contract
#   assertions:
#     purity: pure # This file is declarative configuration.
#     state_ownership: none
#     external_io: https_apis # Interacts with GitHub Actions.

name: 'Whose Turn Now CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: 'Build, Lint, and Test'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from the repository
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Step 2: Set up pnpm, our package manager
      - name: 'Set up pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Use a recent version of pnpm

      # Step 3: Set up the correct version of Node.js
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Cache our dependencies for faster runs

      # Step 4: Install all project dependencies
      - name: 'Install dependencies'
        run: pnpm install

      # Step 5: Run the linter to ensure code style is consistent.
      - name: 'Run linter'
        run: pnpm lint

      # Step 6: Run the build command to ensure the code is valid.
      - name: 'Run build'
        run: pnpm build

      # Step 7: Run the test suite to ensure our business logic is correct.
      - name: 'Run tests'
        run: pnpm test